apiVersion: v1
kind: Service
metadata:
  name: database-primary-headless
  namespace: racunovodstvo-dev
  labels:
    app: database-primary
spec:
  clusterIP: None
  ports:
    - name: database-prim
      port: 3306
  selector:
    app: database-primary
