apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init-scripts-cm
  namespace: racunovodstvo-dev
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS user;
    CREATE DATABASE IF NOT EXISTS preduzece;
    CREATE DATABASE IF NOT EXISTS nabavka;
    CREATE DATABASE IF NOT EXISTS knjizenje;
