apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-primary
  namespace: racunovodstvo-dev
  labels:
    app: database-primary
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: database-primary
  serviceName: database-primary-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database-primary
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - database-primary
                namespaces:
                  - "racunovodstvo-dev"
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: database-primary
          image: docker.io/bitnami/mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_REPLICATION_MODE
              value: master
            - name: MYSQL_REPLICATION_USER
              value: repl_user
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-replication-password
          ports:
            - name: database-prim
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: database-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: database-init-scripts
          configMap:
            name: database-init-scripts-cm
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "8Gi"
