apiVersion: v1
kind: Service
metadata:
  name: database-secondary
  namespace: racunovodstvo-dev
  labels:
    app: database-secondary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: database-sec
      port: 3306
  selector:
    app: database-secondary
