apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: racunovodstvo-prod
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/raf-si-2021/racunovodstvo-front:k8s
          name: racunovodstvo-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: frontend
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: racunovodstvo-prod
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: frontend-http
      port: 80
      targetPort: 80
      protocol: TCP
